### ISSUE TITLE
Black Image returned when cropping large images with higher resolution especially raw camera photos, tried it with a (3456 * 4608) . It doesn't crash though.

### ISSUE THREAD

**Issue by DevLuke67** [Drjacky/ImagePicker#100]

**Comment by DevLuke67** [comment]
`galleryLauncher.launch(
                ImagePicker.with(this@Chats)
                    .crop()
                    .galleryOnly()
                    .setMultipleAllowed(true)
                    .cropFreeStyle()
                    .galleryMimeTypes( // no gif images at all
                        mimeTypes = arrayOf(
                            "image/png",
                            "image/jpg",
                            "image/jpeg"
                        )
                    )
                    .createIntent()
            )`


![Screenshot_20230602-233517](https://github.com/Drjacky/ImagePicker/assets/60089540/f03568d2-6dfa-4eae-9fae-f30cf6b022a7)

**Comment by AkkiKulshrestha** [comment]
Same issue appears at my end as well when clicking picture from camera, in crop screen black screen appears for cropping and gives the same as file. Can you suggest wat needs to be done. 
![Uploading IMG-20230606-WA0024.jpg…]()

**Comment by AkkiKulshrestha** [comment]
![IMG-20230606-WA0023](https://github.com/Drjacky/ImagePicker/assets/38714548/1f22e9f5-9517-4218-9b33-67912443e832)

**Comment by amitkumartiwaridis** [comment]
@Drjacky When I am taking picture from the camera and going to the crop option it only shows a black screen.

**Comment by Drjacky** [comment]
Is it a big picture in size and width/height matters @amitkumartiwaridis.

__

@DevLuke67 please add description and/or edit title

**Comment by Drjacky** [comment]
@DevLuke67 It's an issue with the used internal Image Cropper library: https://github.com/Yalantis/uCrop
Please open the ticket there.
