### ISSUE TITLE
Setting up different languages

### ISSUE THREAD

**Issue by andreacarpibomber** [Drjacky/ImagePicker#101]
How can I change the language to spanish?

**Comment by Drjacky** [comment]
It already supports Spanish: https://github.com/Drjacky/ImagePicker/tree/master/imagepicker/src/main/res

When the device OS locale is set to Spanish, the library detects it automatically.

But if you want it to be always Spanish, you need to move the Strings from `es` to the main `strings.xml` in the `values`(which contains English right now)
