### ISSUE TITLE
Android 13 not workinf

### ISSUE THREAD

**Issue by usmanabid94** [Drjacky/ImagePicker#102]
When we try to use it with gallery only nothing happens it is not working:
@Drjacky 

 ImagePicker.with(this)
                        .provider(ImageProvider.GALLERY) //Or bothCameraGallery()
                        .createIntent();

**Comment by xm75soft** [comment]
[2.3.19] - 2022-09-20
Improve dismiss listener
Update Java version to 11
Support Android API 33
--
@Drjacky
As i checked your history change [2.3.19] - 2022-09-20 but Picker didn't work.
Did you add Android 33 permission ? 
<uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />

**Comment by usmanabid94** [comment]
@xm75soft i have actually moved to using another repo you can close it for now

**Comment by Drjacky** [comment]
You're always welcome to open a PR and I'll merge it.

**Comment by usmanabid94** [comment]
@Drjacky Sure👍
