### ISSUE TITLE
WRITE_EXTERNAL_STORAGE is denied between Sdk 29 and 33.

### ISSUE THREAD

**Issue by EzequielAdrianM** [Drjacky/ImagePicker#103]
Why does the manifest of this library states WRITE_EXTERNAL_STORAGE maxSdkVersion=28?

This is causing my app's merged Manifest  to lose WRITE_EXTERNAL_STORAGE permission in API level >28.
But this permission is still useful up to TIRAMISU. (API 33).

**Comment by Drjacky** [comment]
https://support.google.com/googleplay/android-developer/answer/10467955?hl=en

https://developer.android.com/training/data-storage

**Comment by DhinaMob** [comment]
@Drjacky We have to handle the  "MANAGE_EXTERNAL_STORAGE" permission instead of the "WRITE_EXTERNAL_STORAGE" right?
