### ISSUE TITLE
Screen Orientation Issue: Image Picker

### ISSUE THREAD

**Issue by swapneshagrawal-tudip** [Drjacky/ImagePicker#109]
I am launching the image picker on the landscape mode of my tab application but as soon as It opens the camera and crops the image it changes to portrait mode. due to which my existing activity gets killed. 

Any Suggestion to overcome this issue.

@Drjacky

**Comment by Drjacky** [comment]
Haven't tried but you need to have something like
```xml
<activity
        android:name="com.yalantis.ucrop.UCropActivity"
        android:screenOrientation="landscape"
        android:configChanges="orientation|screenSize|keyboardHidden" />
```
in your application, and then use merge manifest: https://developer.android.com/build/manage-manifests

**Comment by swapneshagrawal-tudip** [comment]
@Drjacky Heyy I took a clone of the repo and removed the **android:screenOrientation="landscape"** from Manifest and it worked. But I am using your repo as the dependency in my project. So I am not sure how to change the manifest file then. I tried to fork the repo and use my repo as dependency but it also did not worked.

**Comment by Drjacky** [comment]
without forking uCrop or ImagePicker repo; just have that ☝🏼 snippet in your app's AndroidManifest.xml. Then probably it compiles shows a manifest conflict error. So, you need to merge both AndroidManifests (https://developer.android.com/build/manage-manifests#override_uses-sdk_for_imported_libraries)

**Comment by swapneshagrawal-tudip** [comment]
@Drjacky Thanks a lot for the solution It Worked.
