### ISSUE TITLE
Camera no work

### ISSUE THREAD

**Issue by Leeeeerich** [Drjacky/ImagePicker#11]
1. Camera no opening.
2. cropOval() no work.

Version: 1.8.1

**Comment by Drjacky** [comment]
- What Android version?
- Do you have that issue on the sample app as well?

**Comment by Leeeeerich** [comment]
1. I used an emulator, Android version 11. But 1.7.10 version camera is working.
2. Sorry, I don't understand the ask.

**Comment by Drjacky** [comment]
@Leeeeerich Please try to install this sample app: https://github.com/Drjacky/ImagePicker/tree/master/sample
And check if you have the issue or not.

Apart from that, if you could put a breakpoint and check, it could help. To have more logcat added in this issue.

**Comment by Leeeeerich** [comment]
Hey! Yes, android:requestLegacyExternalStorage="true" was be installed. When I compile project, 

![untitled](https://user-images.githubusercontent.com/26391015/115410899-b4603800-a1fb-11eb-8bd0-bcd3edb19842.gif)

**Comment by Drjacky** [comment]
@Leeeeerich Please try this and let me know if it works: [v2.0.4](https://github.com/Drjacky/ImagePicker/releases/tag/2.0.4)

**Comment by Drjacky** [comment]
@Leeeeerich Please try the latest version: [v2.0.5](https://github.com/Drjacky/ImagePicker/releases/tag/2.0.5)

Now, the library works on API 19-30 without any problem.

**Comment by Drjacky** [comment]
@Leeeeerich Please try the latest version [v2.1.6](https://github.com/Drjacky/ImagePicker/releases/tag/2.1.6) that has the fix regards issue on API 29.
