### ISSUE TITLE
Can you resolve your copyright issue on fossa(I think gif and some url are same)

### ISSUE THREAD

**Issue by vishalkumarsinghvi** [Drjacky/ImagePicker#17]
I am attaching a screenshot or you can scroll in the end on your library 
<img width="487" alt="Screenshot 2021-05-03 at 11 54 40 AM" src="https://user-images.githubusercontent.com/17532631/116846682-7a812f80-ac06-11eb-817a-92c85023089d.png">

**Comment by Drjacky** [comment]
Fixed.
