### ISSUE TITLE
open failed: EACCES (Permission denied)

### ISSUE THREAD

**Issue by ArisChoice** [Drjacky/ImagePicker#18]
open failed: EACCES (Permission denied)

Not able to select image from gallery

Device Android 10
 minSdkVersion 22
        targetSdkVersion 30

**Comment by Drjacky** [comment]
@ArisChoice Thanks! Yes, I'm aware of the issue; It's related to the [uCrop](https://github.com/Yalantis/uCrop) library.
I'm working on this.

**Comment by Drjacky** [comment]
@ArisChoice The issue on API 29 has been solved in [v2.1.6](https://github.com/Drjacky/ImagePicker/releases/tag/2.1.6).
