### ISSUE TITLE
How to use on Java. Could you give some sample

### ISSUE THREAD

**Issue by ioviov** [Drjacky/ImagePicker#19]
Hi! A lot of thanks for your job!

I used before https://github.com/Dhaval2404/ImagePicker , but Google send a letter "We've detected that your app contains the requestLegacyExternalStorage flag in the manifest file of 1 or more of your app bundles or APKs."

And I found your comments and your library, so...

My old code was:

```
private void avatarTouch() {
        ImagePicker.Companion.with(this)
                .crop(1f, 1f)
                .compress(1024)
                .maxResultSize(1080, 1080)
                .start();
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
        super.onActivityResult(requestCode, resultCode, data);

        if (resultCode == Activity.RESULT_OK) {

            Uri uri = data.getData();
            //File file = ImagePicker.Companion.getFile(data);
            //String filePath = ImagePicker.Companion.getFilePath(data);

            if (uri != null) {
                Picasso.get().load(uri).into(viewManager.avatarImageView);
            }

        } else if (resultCode == ImagePicker.RESULT_ERROR) {
            // Error
            Map<String, String> map = new HashMap<>();
            map.put("error", ImagePicker.Companion.getError(data));
            FirebaseModel.shared().sendAnalytics(MyApplication.context, "image_picker_error", map);

            Toast.makeText(MyApplication.context, ImagePicker.Companion.getError(data), Toast.LENGTH_LONG).show();
        } else {
            // Cancel
        }
    }
```

Could you please help me to change my code. I can't find an example on java how to use your library :(
Thanks!

**Comment by Drjacky** [comment]
https://github.com/Drjacky/ImagePicker/issues/12#issuecomment-817367508

+

https://developer.android.com/training/basics/intents/result#java

**Comment by ioviov** [comment]
I'm sorry
I see errors in builder, as I understand in your library there are no thees methods, see attached files.

<img width="448" alt="Screenshot at May 05 16-21-45" src="https://user-images.githubusercontent.com/13030116/117148222-b3fc9b00-adbe-11eb-8d9d-a2420792749d.png">

<img width="457" alt="Screenshot at May 05 16-22-01" src="https://user-images.githubusercontent.com/13030116/117148277-c2e34d80-adbe-11eb-8a3c-a4a02f13a2a9.png">

In Readme I see:

> ImagePicker.Companion.with(this)
>         .crop()	    			//Crop image(Optional), Check Customization for more option
>         .cropOval()	    		//Allow dimmed layer to have a circle inside
>         .compress(1024)			//Final image size will be less than 1 MB(Optional)
>         .maxResultSize(1080, 1080)	//Final image resolution will be less than 1080 x 1080(Optional)
>         .start()

**Comment by Drjacky** [comment]
You're right. I need to edit the Readme.
There is no need for `compress` method; It has been removed since it was comparing the size of the file and not the image, and the resize operation is enough to reduce the size of the final file.

Thanks for addressing this.

**Comment by Drjacky** [comment]
@ioviov Instead of `start()`, use `createIntent()`

**Comment by ioviov** [comment]
@Drjacky  I tried using `createIntent()` on simulator and real phone, but it's not working, nothing appears.
Possibly in version 2.1.6 this fixed, I will try

Also in Readme you wrote `maxResultSize(1080, 1080)` but for java you should use `maxResultSize(1080, 1080, false)`

**Comment by ioviov** [comment]
I tried use 2.1.6 but during Sync task I see error

<img width="1143" alt="Screenshot at May 06 11-57-07" src="https://user-images.githubusercontent.com/13030116/117271156-95e87680-ae62-11eb-8ca4-0fefb11c69a2.png">

**Comment by Drjacky** [comment]
@ioviov Please test [v2.1.7](https://github.com/Drjacky/ImagePicker/releases/tag/2.1.7) and let me know if the issue solved or not.

**Comment by Drjacky** [comment]
@ioviov Sorry, maven has an issue right now. It doesn't accept new uploads.
Right now, it's on JitPack: https://jitpack.io/#Drjacky/ImagePicker/2.1.7

**Comment by ioviov** [comment]
It's ok
Sorry, I'm not guru on Java, so I need to wait? Or what I should to do right now?
Thanks!

**Comment by ioviov** [comment]
Well I have the same

<img width="905" alt="Screenshot at May 07 20-57-58" src="https://user-images.githubusercontent.com/13030116/117490071-01bc0380-af77-11eb-8efd-6182cec1c80e.png">

And

<img width="826" alt="Screenshot at May 07 20-59-27" src="https://user-images.githubusercontent.com/13030116/117490165-2021ff00-af77-11eb-8179-c7bbdd3e1b00.png">

**Comment by ioviov** [comment]
And

<img width="652" alt="Screenshot at May 07 21-00-53" src="https://user-images.githubusercontent.com/13030116/117490350-53fd2480-af77-11eb-9d0c-81a92bf122ed.png">

**Comment by ioviov** [comment]
@Drjacky Well, it's ok
**Manifest merge failed** is fixed now, thanks!

But `createIntent()` still not working
When I tap on View nothing happens

**Comment by Drjacky** [comment]
Could you create a sample project and attach it here?

**Comment by ioviov** [comment]
Ok, I will do it on next week (I'll try on Monday), thanks

**Comment by Drjacky** [comment]
@ioviov 
[SampleImagePicker-Solution.zip](https://github.com/Drjacky/ImagePicker/files/6459254/SampleImagePicker-Solution.zip)

You would need to define which one you want: `galleryOnly`, `cameraOnly`;
And if you want both, the `createIntent` changes to `createIntentFromDialog`.

P.S I've improved some other parts too. Good to check.

**Comment by Drjacky** [comment]
[v2.1.8](https://github.com/Drjacky/ImagePicker/releases/tag/2.1.8) released.
