### ISSUE TITLE
Cannot select pictures on Huawei P30 Pro using sample

### ISSUE THREAD

**Issue by ydmmocoo** [Drjacky/ImagePicker#2]
Android version：10

**Comment by Drjacky** [comment]
This issue was closed because it has been inactive.

Try the latest version. It has to work.

**Comment by Drjacky** [comment]
@yamin8000 Please try the latest version [v2.1.6](https://github.com/Drjacky/ImagePicker/releases/tag/2.1.6) that has the fix regards issue on API 29.
