### ISSUE TITLE
Black background when cropping image

### ISSUE THREAD

**Issue by devyo12** [Drjacky/ImagePicker#23]
When selecting transparent image/logo display black background in ImageView

**Comment by Drjacky** [comment]
I've tested and the black background is only in the crop step and the result after that has the transparency.
<img src="https://user-images.githubusercontent.com/2296754/118393951-a904fe80-b639-11eb-9de3-093b8bda33f2.png" width="300px" /> <img src="https://user-images.githubusercontent.com/2296754/118393948-a3a7b400-b639-11eb-815d-3d78dada3604.png" width="300px" />

**Comment by devyo12** [comment]
Hi i have check in my app it showing black only 
can you send me code what step you are using

**Comment by Drjacky** [comment]
@devyo12 Just run the sample app: https://github.com/Drjacky/ImagePicker/tree/master/sample
