### ISSUE TITLE
requestLegacyExternalStorage

### ISSUE THREAD

**Issue by maned3v** [Drjacky/ImagePicker#3]
Hi there

I wanted to point out that the requestLegacyExternaStorage flag in the Manifest will be ignored when targhetting Android 11.

[https://developer.android.com/about/versions/11/privacy/storage](url)

> Apps that run on Android 11 but target Android 10 (API level 29) can still request the requestLegacyExternalStorage attribute. >This flag allows apps to temporarily opt out of the changes associated with scoped storage, such as granting access to different >directories and different types of media files. **After you update your app to target Android 11, the system ignores the >requestLegacyExternalStorage flag**.

**Comment by Verdant90** [comment]
Any plans on removing this requirement?

**Comment by Drjacky** [comment]
@maned3v & @Verdant90 @Leeeeerich Please try this version and let me know if it works: [v2.0.4](https://github.com/Drjacky/ImagePicker/releases/tag/2.0.4)

**Comment by Drjacky** [comment]
@Verdant90 @maned3v 
Please try the latest version: [v2.0.5](https://github.com/Drjacky/ImagePicker/releases/tag/2.0.5)

Now, the library works on API 19-30 without any problem.

**Comment by Drjacky** [comment]
@maned3v @Verdant90 Please try the latest version [v2.1.6](https://github.com/Drjacky/ImagePicker/releases/tag/2.1.6) that has the fix regards issue on API 29.
