### ISSUE TITLE
Customize saving behavior for selected and cropped image

### ISSUE THREAD

**Issue by dev-gvs** [Drjacky/ImagePicker#31]
**Is your feature request related to a problem? Please describe.**
I don't want to keep the selected image in the storage, only cropped one. And now, my only option is to manually delete it. 

**Describe the solution you'd like**
Builder option, something like `.saveOnlyCroppedImg()`.

**Describe alternatives you've considered**
Return both image URIs for the activity result.

**Additional context**
I think it definitely belongs here, because this library stores both images and appends suffixes to them by default. And it would be nice to have the ability to customize this behavior. 🙂

**Comment by Drjacky** [comment]
@dev-gvs I'll try to work on this but, always feel free to create a PR and do the change/feature

**Comment by Drjacky** [comment]
Please try [2.3.17](https://github.com/Drjacky/ImagePicker/releases/tag/2.3.17). I have tried to delete both of them.
Now you have the cropped one URI; Do whatever you want with that.
