### ISSUE TITLE
Gallery text on Dialog option 'y' text seem cropped 

### ISSUE THREAD

**Issue by Gagandeep0312** [Drjacky/ImagePicker#34]
**Describe the bug**
Call createIntentFromDialog option , Camera and gallery option displayed. where Y of gallery text shows cropped from bottom.

**Expected behavior**
Both Camera and Gallery text should be clear visible without cropped text

**Screenshots**

**Smartphone (please complete the following information):**
 - Device:  RealMe XT
- XXHDPI

![Screenshot_2021-09-06-16-16-21-01_d51d67da3b25686056ad1503b0054826](https://user-images.githubusercontent.com/83349803/132206093-7a71ab6c-5a0e-4685-af5b-f782dcbe838c.jpg)

**Comment by Drjacky** [comment]
I increased the font size but, couldn't reproduce the issue!
<img src="https://user-images.githubusercontent.com/2296754/132215520-0867164f-fde6-4c63-958d-83c0e19b50c5.png" width="300px" />

**Comment by Gagandeep0312** [comment]
Can you try it out with this specification. This is my phone screen,
2340-by-1080-pixel resolution at 402 ppi

**Comment by Drjacky** [comment]
@Gagandeep0312 If you could create, export and attach it here, would be great.

**Comment by Gagandeep0312** [comment]
Hey @Drjacky I already added the screenshot of screen, what needs to attach more ?

**Comment by Gagandeep0312** [comment]
Can you share a build with me for the same. I will test check at my end.

**Comment by Drjacky** [comment]
@Gagandeep0312 I meant the emulator config.
You create what you want in the AVD Manager, then export it and attach the zip here.

The sample app would work: https://github.com/Drjacky/ImagePicker/tree/master/sample

**Comment by Gagandeep0312** [comment]
Hi @Drjacky , Thank you for patience and communication. Finally I found the issue, its on me. Kindly close this issue.
