### ISSUE TITLE
[Question] - Android versions

### ISSUE THREAD

**Issue by GuilhE** [Drjacky/ImagePicker#36]
Hello @Drjacky , I hope this message finds you well.
Remember this [conversation](https://github.com/Dhaval2404/ImagePicker/pull/171)? Does your lib manages to solve this restrictions/findings?

Regards.

**Comment by Drjacky** [comment]
Hi @GuilhE,
Yes, it is solved.
I continued your work and changed some classes and methods and now, it works.
