### ISSUE TITLE
Now able to add imagePicker 

### ISSUE THREAD

**Issue by rbhagwane123** [Drjacky/ImagePicker#39]
![Screenshot 2021-09-25 215018](https://user-images.githubusercontent.com/84093647/134778480-b0dc4a75-3823-45d3-af83-41acfbcc56dc.png)

This error occurring on adding a jitpack.io on gradle sync. So Please help me to fix this

**Comment by Drjacky** [comment]
Please add your `build.gradle`s; All of them.

**Comment by nirmal700** [comment]
Add jitpack.io in Settings.gradle

**Comment by Drjacky** [comment]
https://github.com/Drjacky/ImagePicker/issues/47
