### ISSUE TITLE
selecting image from gallery

### ISSUE THREAD

**Issue by uzairmughal3397** [Drjacky/ImagePicker#4]
App crashes without any error when selecting image from gallery.

**Comment by Drjacky** [comment]
This issue was closed because it has been inactive.

Please try the latest version from the release section. It has to work.

**Comment by Drjacky** [comment]
@uzairmughal3397 Please try the latest version [v2.1.6](https://github.com/Drjacky/ImagePicker/releases/tag/2.1.6) that has the fix regards issue on API 29.
