### ISSUE TITLE
Pick Multiple Images?

### ISSUE THREAD

**Issue by shafayatb** [Drjacky/ImagePicker#41]
Hi, Is there an option to pick multiple images? Thanks.

**Comment by rrsaikat** [comment]
Need multiple image selection feature! 
Its 2022, still thinking to enhance this feature bro? @Drjacky

**Comment by Drjacky** [comment]
@rrsaikat Feel free to add the feature and open a PR 🙏🏼

**Comment by GliTcH-5** [comment]
is this Feature Available now ?
if No then is there any Work around to Multi-select Images ??

**Comment by Drjacky** [comment]
It's available on [2.3.17](https://github.com/Drjacky/ImagePicker/releases/tag/2.3.17)
