### ISSUE TITLE
Not working well

### ISSUE THREAD

**Issue by Umeshekh** [Drjacky/ImagePicker#44]
I have added the required repositories and dependency but still not working

**Comment by zelyasa** [comment]
Yes the same here, the implementation was case sensitive you responded here  `implementation 'com.github.Drjacky:ImagePicker:2.1.14'`  butin the wiki `implementation 'com.github.Drjacky:imagepicker:2.1'`
thank you and an other problem is that i get Failed to resolve: com.github.yalantis:ucrop:2.2.7 i think this is related to your lib

**Comment by Drjacky** [comment]
@Umeshekh Let me know if after adding the repo, it worked or not.

@zelyasa https://github.com/Drjacky/ImagePicker/issues/45#issuecomment-962007033
