### ISSUE TITLE
not work - both camera and gallery

### ISSUE THREAD

**Issue by Ziv-Gimani** [Drjacky/ImagePicker#46]
hi, 
I try to allow access to both the camera and the gallery.
When I run the app it crashes
Would appreciate help.

i used with this code:
```java
   ImagePicker.Companion.with(this)
                       .crop()
                       .cropOval()
                       .maxResultSize(512, 512, true)
                       .createIntentFromDialog((Function1) (new Function1() {
                           public Object invoke(Object var1) {
                               this.invoke((Intent) var1);
                               return Unit.INSTANCE;
                           }

                           public final void invoke(@NotNull Intent it) {
                               Intrinsics.checkNotNullParameter(it, "it");
                               launcher.launch(it);
                           }
                       }));
```

***
when i used with this code- only gallery was open and camera crashes:
```java
ImagePicker.Companion.with(HomePageActivity.this)
                        .crop()
                        //.cropOval()
                        //.compress(1024)
                        .maxResultSize(1080,1080)
                        .galleryMimeTypes(mimeTypes)
                        .start();
```

Java language

**Comment by Drjacky** [comment]
Please put the crash logcat to the question as well.

**Comment by Ziv-Gimani** [comment]
![bug](https://user-images.githubusercontent.com/44395362/140949750-bceedaaa-93e0-48d0-9a1d-c3329299590d.png)

**Comment by Drjacky** [comment]
Please download and open it in the Android Studio and compare it with yours; Probably you do not have the necessary imports.
https://github.com/Drjacky/ImagePicker/issues/19#issuecomment-838434841

**Comment by Ziv-Gimani** [comment]
im really sorry to bother you, but i work step by step with your video on youTube, and everything was fine except the access to camera so i tried to add the code you wrote for both and import all but still not working.

i tried to check the camera access alone and my app still crushes.

**Comment by Drjacky** [comment]
Please put the link to the video here.
Also, open the sample app I've mentioned above and take a screenshot of the whole screen including the errors.

**Comment by Ziv-Gimani** [comment]
[link:](https://www.youtube.com/watch?v=kWeeWOlzEKM)

![image](https://user-images.githubusercontent.com/44395362/140968825-1a55587c-3558-48b5-9ac6-28b7cc7b43ac.png)

p.s.
the sample app get access only to gallery, and i dont have problem with this acess in my app.
i have struglle to get camera acess

**Comment by Drjacky** [comment]
That youtube is not from mine. He's just using my library.

Replace `launcher` with `galleryLauncher` + and you're in Fragment. So, to be able to refer to Activity, you cannot use `this`(like 72).
Add `implementation 'androidx.fragment:fragment-ktx:1.3.6'` and use `requiredActivity`
Or
use `getActivity`
