### ISSUE TITLE
Uctop error can't build gradle

### ISSUE THREAD

**Issue by ahamedibrahim2002** [Drjacky/ImagePicker#49]
Please help me am  working on camera, I am unable to build gradle constantly getting error in ucrop![build output.png](https://user-images.githubusercontent.com/81787066/142250707-90357b3c-e8c0-434c-b596-7fefa3e36534.png)![build gradle.png](https://user-images.githubusercontent.com/81787066/142250736-b5497656-859a-4ad5-b74d-f2d6f50a3914.png)![build gradle app 1.png](https://user-images.githubusercontent.com/81787066/142250739-c4a22a25-e749-4424-8f74-82b818b500e8.png)![build gradle app 2.png](https://user-images.githubusercontent.com/81787066/142250745-b45a4013-31eb-4d45-9294-495075ad8376.png)![manifest.png](https://user-images.githubusercontent.com/81787066/142250754-405e7058-9dbe-4c47-a7d7-5cb38c82546e.png)

**Comment by Drjacky** [comment]
https://github.com/Drjacky/ImagePicker/issues/47
