### ISSUE TITLE
How to open Stock Gallery App not a File / Document App ?

### ISSUE THREAD

**Issue by mongkonsrisin** [Drjacky/ImagePicker#5]
I'm using this code

`ImagePicker.with(this)
	.galleryOnly()	//User can only select image from Gallery
	.start()	//Default Request Code is ImagePicker.REQUEST_CODE`

It opens File / Document App not a Gallery App ?

**Comment by Drjacky** [comment]
Please check if you have the same issue on the [sample app](https://github.com/Drjacky/ImagePicker/tree/master/sample).
Also, what is the Android version?

**Comment by Drjacky** [comment]
@mongkonsrisin Please check it on [v2.1.6](https://github.com/Drjacky/ImagePicker/releases/tag/2.1.6) and let me know if the issue has been fixed or not.
