### ISSUE TITLE
Could not find com.github.yalantis:ucrop:2.2.7

### ISSUE THREAD

**Issue by dinukapj** [Drjacky/ImagePicker#50]
Getting a 'Not found' gradle error for ucrop on a kotlin project. Tried manually adding that to the gradle as well.

```
Execution failed for task ':app:mergeDebugNativeLibs'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.yalantis:ucrop:2.2.7.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/yalantis/ucrop/2.2.7/ucrop-2.2.7.pom
       - https://repo.maven.apache.org/maven2/com/github/yalantis/ucrop/2.2.7/ucrop-2.2.7.pom
       - https://jcenter.bintray.com/com/github/yalantis/ucrop/2.2.7/ucrop-2.2.7.pom
     Required by:
         project :app
   > Could not find com.github.yalantis:ucrop:2.2.7.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/yalantis/ucrop/2.2.7/ucrop-2.2.7.pom
       - https://repo.maven.apache.org/maven2/com/github/yalantis/ucrop/2.2.7/ucrop-2.2.7.pom
       - https://jcenter.bintray.com/com/github/yalantis/ucrop/2.2.7/ucrop-2.2.7.pom
     Required by:
         project :app > com.github.Drjacky:ImagePicker:2.1.15
```

**Comment by ahamedibrahim2002** [comment]
> Getting a 'Not found' gradle error for ucrop on a kotlin project. Tried manually adding that to the gradle as well.
> 
> ```
> Execution failed for task ':app:mergeDebugNativeLibs'.
> > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
>    > Could not find com.github.yalantis:ucrop:2.2.7.
>      Searched in the following locations:
>        - https://dl.google.com/dl/android/maven2/com/github/yalantis/ucrop/2.2.7/ucrop-2.2.7.pom
>        - https://repo.maven.apache.org/maven2/com/github/yalantis/ucrop/2.2.7/ucrop-2.2.7.pom
>        - https://jcenter.bintray.com/com/github/yalantis/ucrop/2.2.7/ucrop-2.2.7.pom
>      Required by:
>          project :app
>    > Could not find com.github.yalantis:ucrop:2.2.7.
>      Searched in the following locations:
>        - https://dl.google.com/dl/android/maven2/com/github/yalantis/ucrop/2.2.7/ucrop-2.2.7.pom
>        - https://repo.maven.apache.org/maven2/com/github/yalantis/ucrop/2.2.7/ucrop-2.2.7.pom
>        - https://jcenter.bintray.com/com/github/yalantis/ucrop/2.2.7/ucrop-2.2.7.pom
>      Required by:
>          project :app > com.github.Drjacky:ImagePicker:2.1.15
> ```

S bro same for me I am still waiting

**Comment by ahamedibrahim2002** [comment]
> Getting a 'Not found' gradle error for ucrop on a kotlin project. Tried manually adding that to the gradle as well.
> 
> ```
> Execution failed for task ':app:mergeDebugNativeLibs'.
> > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
>    > Could not find com.github.yalantis:ucrop:2.2.7.
>      Searched in the following locations:
>        - https://dl.google.com/dl/android/maven2/com/github/yalantis/ucrop/2.2.7/ucrop-2.2.7.pom
>        - https://repo.maven.apache.org/maven2/com/github/yalantis/ucrop/2.2.7/ucrop-2.2.7.pom
>        - https://jcenter.bintray.com/com/github/yalantis/ucrop/2.2.7/ucrop-2.2.7.pom
>      Required by:
>          project :app
>    > Could not find com.github.yalantis:ucrop:2.2.7.
>      Searched in the following locations:
>        - https://dl.google.com/dl/android/maven2/com/github/yalantis/ucrop/2.2.7/ucrop-2.2.7.pom
>        - https://repo.maven.apache.org/maven2/com/github/yalantis/ucrop/2.2.7/ucrop-2.2.7.pom
>        - https://jcenter.bintray.com/com/github/yalantis/ucrop/2.2.7/ucrop-2.2.7.pom
>      Required by:
>          project :app > com.github.Drjacky:ImagePicker:2.1.15
> ```

Found just add  maven{url "https://jitpack.io" }
in settings.gradle below repositories{......}

**Comment by Drjacky** [comment]
https://github.com/Drjacky/ImagePicker/issues/47
