### ISSUE TITLE
Define Picture Output Format (e.g. WebP) 

### ISSUE THREAD

**Issue by fairEnough83** [Drjacky/ImagePicker#51]
**Is your feature request related to a problem? Please describe.**
Currently you cannot define output format and the origin format is used. If you pick a jpg file and crop it you have to convert to webp on your own

**Describe the solution you'd like**
On the library level it would be easy to convert e.g.

FileOutputStream out = new FileOutputStream(path); 
bitmap.compress(Bitmap.CompressFormat.WEBP, 100, out);
out.close();

**Comment by Drjacky** [comment]
It's available on [2.3.17](https://github.com/Drjacky/ImagePicker/releases/tag/2.3.17)
