### ISSUE TITLE
2.1.15 is not opening picker. 2.1.14 is working

### ISSUE THREAD

**Issue by fairEnough83** [Drjacky/ImagePicker#52]
**Describe the bug**
Hard to say because I did not see anything in logcat. App has target api 31 as well. Invocation is within jetpack compose. Please give me further instructions to assist

**To Reproduce**
Steps to reproduce the behaviour:

ImagePicker.with(context as Activity)
                                        .maxResultSize(maxAvatarSize, maxAvatarSize)
                                        .cropSquare()
                                        .createIntentFromDialog { launcher.launch(it) }

**Expected behavior**

Image picker is opened

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
- Emulator
- Xiaomi Redmi 10s
- Galaxy S21

all of my phones

**Comment by Drjacky** [comment]
Could you add a sample project to the ticket?

**Comment by MartinMbae** [comment]
Having similar challenge. Image picker is not opened. Nothing in the Logcat.
I am using 


                ImagePicker.with(requireActivity())
                    .crop()
                    .cropFreeStyle()
                    .createIntentFromDialog { launcher.launch(it) }

**Comment by Drjacky** [comment]
@MartinMbae Please attach a sample app. and on which Android version did you see this issue?

**Comment by Sasikumars41** [comment]
This will work. Important line for createIntentFromDialog  is  to add provider(ImageProvider.BOTH). Refer below
  ImagePicker.with(context)
                .crop()
                .cropSquare()
                .maxResultSize(320, 320, true)
                .galleryMimeTypes(arrayOf("image/png", "image/jpg", "image/jpeg"))
                **.provider(ImageProvider.BOTH)**
                .createIntentFromDialog { launcher.launch(it) }

**Comment by fairEnough83** [comment]
I can confirm that this is fixing the issue

 .provider(ImageProvider.BOTH) ftw

Thank you
