### ISSUE TITLE
Does this support for choose video and capture video?

### ISSUE THREAD

**Issue by Mihir3646** [Drjacky/ImagePicker#54]
The library is really well written also the documentation. I need to upload both image and video so.
Please provide the support for the video uploading from both gallery and camera. Not the compressed one for now, but better if it is also included. 

Thank you.

**Comment by Mihir3646** [comment]
Any luck for this?

**Comment by Drjacky** [comment]
@Mihir3646 Sorry for the late reply.
Sorry but, there is no plan(yet) to add the video picking to this library.
