### ISSUE TITLE
Gradle Build Failed Could not find com.github.yalantis:ucrop:2.2.7.

### ISSUE THREAD

**Issue by nirmal700** [Drjacky/ImagePicker#57]
**Describe the bug**
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.yalantis:ucrop:2.2.7.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/yalantis/ucrop/2.2.7/ucrop-2.2.7.pom
       - https://repo.maven.apache.org/maven2/com/github/yalantis/ucrop/2.2.7/ucrop-2.2.7.pom
       - https://jcenter.bintray.com/com/github/yalantis/ucrop/2.2.7/ucrop-2.2.7.pom
     Required by:
         project :app > com.github.Drjacky:ImagePicker:2.1.15

**To Reproduce**
1. Go to 'Gradle build Sync the App and Run '
2. See error

**Expected behavior**
No Error 

**Desktop (please complete the following information):**
 - OS: [e.g. Mac]

**Smartphone (please complete the following information):**

**Additional context**
Language : Java
Android Studio : Artic Fox
Gradle : 8.0.2
Min SDK : 28

**Comment by Drjacky** [comment]
https://github.com/Drjacky/ImagePicker/issues/47
