### ISSUE TITLE
Could not find com.github.yalantis:ucrop:2.2.7.

### ISSUE THREAD

**Issue by Skylernitin** [Drjacky/ImagePicker#59]
* Could not find com.github.yalantis:ucrop:2.2.7. 
* update yalantis dependency in your library

**Comment by Drjacky** [comment]
It is 2.2.7: https://github.com/Drjacky/ImagePicker/blob/6e5b9abf7675c927eae306e31ba92a9d8de4844e/imagepicker/build.gradle#L52

Please take a look at this: https://github.com/Drjacky/ImagePicker/issues/47
