### ISSUE TITLE
Can't build project

### ISSUE THREAD

**Issue by nxtdesigns** [Drjacky/ImagePicker#62]
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.yalantis:ucrop:2.2.7.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/yalantis/ucrop/2.2.7/ucrop-2.2.7.pom
       - https://repo.maven.apache.org/maven2/com/github/yalantis/ucrop/2.2.7/ucrop-2.2.7.pom
       - https://jcenter.bintray.com/com/github/yalantis/ucrop/2.2.7/ucrop-2.2.7.pom

**Comment by Drjacky** [comment]
Please take a look at this: https://github.com/Drjacky/ImagePicker/issues/47
