### ISSUE TITLE
Showing black screen

### ISSUE THREAD

**Issue by pchauhan** [Drjacky/ImagePicker#64]
**Describe the bug**

**To Reproduce**
1. Go to '..Camera'
2. Click on 'Take Picture'
3. When you come back on app
4. See error - Image won't show .

**Expected behavior**
Should show selected image.

**Screenshots**
 

**Smartphone (please complete the following information):**
 - Device: Samsung note ultra
 - OS: Android 11 
 

Video with facing issue
https://drive.google.com/file/d/1uoUKZDxTqSM_yB7tS4jphcyezQUV87Og/view?usp=sharing

**Comment by Drjacky** [comment]
I didn't get it! What's the issue? I don't do anything with the camera options/features. It should be related to your device/OS. Try reset or other solutions suggested on internet.
