### ISSUE TITLE
ImagePicker dialog not showing in version 2.1.15

### ISSUE THREAD

**Issue by chayanforyou** [Drjacky/ImagePicker#66]
I'm using library version v2.1.15
```groovy
implementation 'com.github.Drjacky:ImagePicker:2.1.15'
```
And my code is

```kotlin
binding.pickImage.setOnClickListener {
            ImagePicker.with(requireActivity())
                .crop()
                .cropOval()
                .maxResultSize(512, 512)
                .createIntentFromDialog { profileLauncher.launch(it) }
        }
```
Handling results
```kotlin
private val profileLauncher = registerForActivityResult(ActivityResultContracts.StartActivityForResult()) {
        if (it.resultCode == Activity.RESULT_OK) {
            val uri = it.data?.data!!
            val filePath = FileUriUtils.getRealPath(requireContext(), uri)
            Log.d("Path", filePath!!)
        }
    }
```
My ImagePicker dialog isn't showing. But if I downgrade the version to `2.1.14` its working fine.

**Comment by yogeshreddoorz** [comment]
I am also facing same issue  on 2.1.15, I just changed 2.1.15 to 2.1.14 its working.

**Comment by itzFaiz** [comment]
This will work. Important line for createIntentFromDialog is to add provider(ImageProvider.BOTH). Refer below

  ImagePicker.with(context)
                .crop()
                .cropSquare()
                .maxResultSize(320, 320, true)
                .galleryMimeTypes(arrayOf("image/png", "image/jpg", "image/jpeg"))
               .provider(ImageProvider.BOTH)
                .createIntentFromDialog { launcher.launch(it) }

**Comment by itzFaiz** [comment]
This will work. Important line for createIntentFromDialog is to add provider(ImageProvider.BOTH). Refer below

`ImagePicker.with(context)
                .crop()
                .cropSquare()
                .maxResultSize(320, 320, true)
                .galleryMimeTypes(arrayOf("image/png", "image/jpg", "image/jpeg"))
               .provider(ImageProvider.BOTH)
                .createIntentFromDialog { launcher.launch(it) }
`

**Comment by itzFaiz** [comment]
This will work. Just add provider (ImageProvider.BOTH). Refer below

``` binding.pickImage.setOnClickListener {
            ImagePicker.with(requireActivity())
                .crop()
                .cropOval()
                .maxResultSize(512, 512)
                .provider(ImageProvider.BOTH)
                .createIntentFromDialog { profileLauncher.launch(it) }
        } ```
