### ISSUE TITLE
Gallery Option does not List gallery app

### ISSUE THREAD

**Issue by rwadada** [Drjacky/ImagePicker#67]
**Is your feature request related to a problem? Please describe.**
The gallery option lists all documents and displays recent images. However, the default Gallery and Google Photos applications are not displayed, so you may not be able to retrieve the images you need.

**Describe the solution you'd like**
I want to change the ACTION set in Intent below to ACTION_GET_CONTENT.
https://github.com/Drjacky/ImagePicker/blob/6e5b9abf7675c927eae306e31ba92a9d8de4844e/imagepicker/src/main/kotlin/com/github/drjacky/imagepicker/util/IntentUtils.kt#L44
Related Issue: https://github.com/Dhaval2404/ImagePicker/issues/263

**Describe alternatives you've considered**
The issue is because the Intent is set to open a document

**Additional context**
Send a PullRequest if necessary.

**Comment by Drjacky** [comment]
It has been fixed on [2.1.16](https://github.com/Drjacky/ImagePicker/releases/tag/2.1.16)
