### ISSUE TITLE
[ bug ] Expect to optimize more UI details to provide better user experience

### ISSUE THREAD

**Issue by lhzlg3368** [Drjacky/ImagePicker#75]
**Describe the bug**
Hi, first of all, I would like to thank the author for the library, which has saved me a lot of time in development.

When I use this library, I expect the colors of the library to be consistent with the theme color of the application so that the user experience is better.
However, the problems in the screenshot are.
1. the status bar part, after setting it to white, the icon color is also white. Expect the status bar to be set to white and the icons to be black.
2. `27%`,`Rotate`,`Scale` are still orange, I expect I can configure it as theme color.

**Screenshots**
<img width="792" alt="image" src="https://user-images.githubusercontent.com/29848244/192481968-87ac1fc3-8925-4c4b-96e3-ec86eb5bc8bd.png">

**Smartphone**
 - Device: [e.g. Pixel3]
 - OS: [e.g.Android.12]
 - Version [e.g. 2.3.19]

**Comment by Drjacky** [comment]
For crop part, I use [uCrop](https://github.com/Yalantis/uCrop). It seems you can customize the style for its `UCropActivity` like this:
```xml
<activity
    android:name="com.yalantis.ucrop.UCropActivity"
    android:screenOrientation="portrait"
    android:theme="@style/Theme.AppCompat.Light.NoActionBar"/>
```

Hope it helps. For further needs on this, you could open an issue on that repository.
