### ISSUE TITLE
Jitpack requires different implementation syntax

### ISSUE THREAD

**Issue by tobiasKaminsky** [Drjacky/ImagePicker#8]
Thanks for your great library!

While trying to use it, I got an error:
```
Could not determine the dependencies of task ':app:compileGplayDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:gplayDebugCompileClasspath'.
   > Could not find :unspecified:.
     Required by:
         project :app > com.github.Drjacky:ImagePicker:1.8.1

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```
This was with: `implementation 'com.github.Drjacky:ImagePicker:1.8.1' `

Changing it to `implementation 'com.github.drJacky:ImagePicker:1.8.1' ` as found on https://jitpack.io/#drJacky/ImagePicker/1.8.1 worked.

**Comment by Drjacky** [comment]
@tobiasKaminsky Would you please try again with implementation 'com.github.Drjacky:ImagePicker:1.8.1'?
I could see the build here: https://jitpack.io/#Drjacky/ImagePicker/1.8.1

In the maven, it's the same:
https://mvnrepository.com/artifact/com.github.Drjacky/ImagePicker/1.8.1
https://search.maven.org/artifact/com.github.Drjacky/ImagePicker/1.8.1/aar

**Comment by Drjacky** [comment]
I've tried with this `implementation 'com.github.drjacky:ImagePicker:1.8.1'` and it worked.
I'm gonna take a look into this later on.

**Comment by tobiasKaminsky** [comment]
implementation 'com.github.Drjacky:ImagePicker:1.8.1' // NOT working
implementation 'com.github.drjacky:ImagePicker:1.8.1' // works
implementation 'com.github.drJacky:ImagePicker:1.8.1' // works

gradle sync is not enough. It only fails when actually trying to build the app.

**Comment by Drjacky** [comment]
@tobiasKaminsky The point is, I've removed `jcenter` from repository. It's only available on `mavenCentral` and `jitpack`.
And it seems the first attempt is with `mavenCentral`.

The `jitpack` is only necessary for the `uCrop` library, as I've mentioned here: https://github.com/Drjacky/ImagePicker#usage

So, better to fetch it from maven.
