### ISSUE TITLE
Support for localization

### ISSUE THREAD

**Issue by devbox-android-dev1** [Drjacky/ImagePicker#81]
**Is your feature request related to a problem? Please describe.**
Is there a way to add localization to the popup, I used this library for english language, now i need to develop this in arabic language.

**Comment by Drjacky** [comment]
We do support Arabic! https://github.com/Drjacky/ImagePicker/blob/master/imagepicker/src/main/res/values-ar/strings.xml

What do you see when the dialogue is prompted?

**Comment by devbox-android-dev1** [comment]
![Screenshot_20221103_153059](https://user-images.githubusercontent.com/107170232/199693498-5915efb9-976d-47af-a4f7-388fc4060292.png)

Seeing english content only.

**Comment by Drjacky** [comment]
And what library version do you use?

**Comment by devbox-android-dev1** [comment]
Updated to the latest version, localization works fine. Thanks!!
