### ISSUE TITLE
Gallery Picker is not opening

### ISSUE THREAD

**Issue by devsarathsvs** [Drjacky/ImagePicker#83]
`    binding.clickImportFromgallery.setOnClickListener {
            ImagePicker.with(this)
                .provider(ImageProvider.GALLERY) //Or bothCameraGallery()
                .createIntentFromDialog {
                    launcher.launch(it)
                }
        }`

when i use ImageProvider.BOTH its working fine, it gives me two options to select from both camera and gallery is working, but when i use ImageProvider.GALLERY, its not launching anything, I just want it to only open from Gallery

**Comment by Drjacky** [comment]
Have you check the sample app?
`createIntentFromDialog` is only for both inputs. for only one of them, you need to use `.createIntent()`

https://github.com/Drjacky/ImagePicker/blob/5858eb2bc44462f439841aa42adce5f8c4165c94/sample/src/main/kotlin/com.github.drjacky.imagepicker/sample/MainActivity.kt#L45-L65

https://github.com/Drjacky/ImagePicker/blob/5858eb2bc44462f439841aa42adce5f8c4165c94/sample/src/main/kotlin/com.github.drjacky.imagepicker/sample/MainActivity.kt#L121-L138
