### ISSUE TITLE
Localization is not working completely

### ISSUE THREAD

**Issue by AbdullahJaved-dev** [Drjacky/ImagePicker#84]
Localization is not working on Crop Activity for Spanish.  

<img src="https://user-images.githubusercontent.com/66158133/202479669-574fcda5-099d-41a6-8abb-0244d3c7b25a.jpg" width="300px" />
<img src="https://user-images.githubusercontent.com/66158133/202479838-5644c27f-cc74-4913-a376-049e519c5a81.jpg" width="300px" />

 - Device: Xiaomi Poco X3 
 - OS: Android 11

**Comment by Drjacky** [comment]
https://github.com/Drjacky/ImagePicker/issues/13#issuecomment-818072121
