### ISSUE TITLE
Could not scale to target size

### ISSUE THREAD

**Issue by x1nming** [Drjacky/ImagePicker#94]
Run sample, select a 100M+image from the album, and crash directly.....

![image](https://user-images.githubusercontent.com/61224872/213415610-e56c8b22-5879-452e-ae74-2267c25c4715.png)

**Comment by Drjacky** [comment]
https://android.googlesource.com/platform/frameworks/base/+/master/libs/hwui/jni/ImageDecoder.cpp#247

https://gerrit.pixelexperience.org/plugins/gitiles/frameworks_base/+/14610721fe355a4f9c7c0cfca62336a09a69cded%5E2..14610721fe355a4f9c7c0cfca62336a09a69cded/
